site_name: LinuxProfile
site_url: http://linuxprofile.com
repo_name: MyLinuxProfile/linux-profile
repo_url: https://github.com/MyLinuxProfile/linux-profile

nav:
    - Home: index.md
    - Installation: nav/installation.md
    - Commands:
        # - Account:
        #     - nav/commands/account/index.md
        #     - nav/commands/account/exemple.md
        - Config:
            - nav/commands/config/index.md
            - nav/commands/config/exemple.md
        - Profile:
            - nav/commands/profile/index.md
            - nav/commands/profile/exemple.md
        - Add:
            - nav/commands/add/index.md
            - nav/commands/add/exemple.md
        - Remove:
            - nav/commands/remove/index.md
            - nav/commands/remove/exemple.md
        - Install:
            - nav/commands/install/index.md
            - nav/commands/install/exemple.md
        - Uninstall:
            - nav/commands/uninstall/index.md
            - nav/commands/uninstall/exemple.md
        - List:
            - nav/commands/list/index.md
            - nav/commands/list/exemple.md
    - Storage: nav/storage.md
    - Backup: nav/backup.md
    - Release Notes: nav/release-notes.md
    - Quick Starter: nav/quick-starter.md

theme: 
    name: material
    logo: assets/linux-profile-icon.png
    favicon: assets/linux-profile-icon.ico
    features:
        - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/MyLinuxProfile
