name: 📦 Package Coverage-Test

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
    - name: ⚙️ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: ⚙️ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt --no-cache-dir
    - name: ❤️️ Test with Coverage
      run: |
        coverage run -m pytest
    - name: ⚙️ Github
      run: |
        git config --global user.email "email@fernandocelmer.com"
        git config --global user.name "FernandoCelmer"
    - name: ⚙️ Settings 
      run: |
        rm -r coverage.svg
        coverage-badge -o docs/coverage.svg
        git add docs/coverage.svg
        git commit -m "📘 DOCS - Update Badge"
        git push
      continue-on-error: true
