name: 📘 Update Docs

on:
  pull_request:
    branches: [ "develop" ]

permissions: read-all

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
    - name: ⚙️ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: ⚙️ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt --no-cache-dir
    - name: 📘 Build Docs
      run: |
        mkdocs build
    - name: 📘 Update Docs
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_PATH: ${{ secrets.FTP_PATH }}
      run: |
        python .github/update_docs.py
